let yourAge= 25
let yearBirth = 1998
let birthNumber = 21
let numberBrothers = 1
let numberSisters = 0
let numberPeople = 4
let costTravel = 50
let thisYear = 2023
let dollar = 84
let euro = 90
let bitcoin = 2000000
let task1 = thisYear - yearBirth
let task2 = thisYear - yourAge
let task3 = numberBrothers + numberSisters
let task4 = euro * 1000
let task5 = dollar * 2.5
let task6 = bitcoin / 10000  
let task7 = costTravel / dollar
let task8 = numberPeople - numberBrothers - numberSisters
let task9 = 0 / yourAge
let task10 = 35 - yourAge
